pre_task:
  - name: cm_scope
    cmd: checkmate affected
    env:
      CM_LIST: $OUTPUT
post_task:
  - name: cm_verify
    cmd: checkmate run --target "$CM_LIST"
post_push:
  - name: cm_regress
    cmd: checkmate run
